apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Other services will connect using this name
spec:
  selector:
    app: mysql # Selects Pods with the label 'app: mysql'
  ports:
    - protocol: TCP
      port: 3306 # Port the service listens on
      targetPort: 3306 # Port on the Pods to forward traffic to
  # type: ClusterIP # Default type, only reachable within the cluster