apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted by only one node at a time
  resources:
    requests:
      storage: 500Mi # Request 500 Megabytes (adjust if needed for cache size)
  # storageClassName: standard # Kind usually has a default 'standard' storage class