apiVersion: v1
kind: Service
metadata:
  name: redis-service # API Gateway will connect using this name
spec:
  selector:
    app: redis # Selects Pods with the label 'app: redis'
  ports:
    - protocol: TCP
      port: 6379 # Port the service listens on
      targetPort: 6379 # Port on the Redis Pods
  type: ClusterIP # Only reachable within the cluster