apiVersion: v1
kind: Service
metadata:
  name: eureka-service # This is the crucial name other services will use
spec:
  selector:
    app: eureka-server # Selects Pods labeled 'app: eureka-server'
  ports:
    - protocol: TCP
      port: 8761 # Service port
      targetPort: 8761 # Pod port
  type: ClusterIP # Only accessible within the cluster