apiVersion: v1
kind: Service
metadata:
  name: user-manager-service # Service name for User Manager
spec:
  selector:
    app: user-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Internal service