apiVersion: v1
kind: Service
metadata:
  name: academic-manager-service
spec:
  selector:
    app: academic-manager
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP