apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        # IMPORTANT: Use the image name you loaded into Kind
        image: my-notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        # *** CRITICAL OVERRIDES ***
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/project"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service" # Use RabbitMQ service name
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID
          value: "config-server"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        readinessProbe:
          # ... (configure probes similar to user-manager on port 8083)
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 35 # Might need longer due to RabbitMQ dependency
          periodSeconds: 10
        livenessProbe:
          # ... (configure probes similar to user-manager on port 8083)
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 70
          periodSeconds: 20