apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80 # Standard HTTP port externally
      targetPort: 9090 # Port the gateway pod listens on
  # Type LoadBalancer tells Kind (via Docker Desktop) to allocate an external IP
  # On Docker Desktop, this will usually be localhost
  type: LoadBalancer